# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97373a166a88571c7a2b71b8d81dae0f1b2a8e1f749a6afb1e0259e4391bd9e44ade6dbda7d32405dabe6da556596a7e05440486b64ce3587ec115031b0b4a8a

test:
  secret_key_base: d6270292538f4532e7c47d42beb2c0a7de532ba45998c659405acf1318f0174d08e2badba38228d6696155bd489ca48605a9f29e37c5ef484554082a53921aaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
